# Generated by Django 3.2.4 on 2021-06-20 21:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210620_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
        migrations.AddField(
            model_name='question',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='questions-picture'),
        ),
        migrations.AddField(
            model_name='question',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='questions-picture'),
        ),
        migrations.AddField(
            model_name='question',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='questions-picture'),
        ),
        migrations.AddField(
            model_name='question',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='questions-picture'),
        ),
        migrations.AddField(
            model_name='question',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='questions-picture'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4'), ('Option5', 'Option5'), ('Picture1', 'Picture1'), ('Picture2', 'Picture2'), ('Picture3', 'Picture3'), ('Picture4', 'Picture4'), ('Picture5', 'Picture5')], max_length=200),
        ),
    ]
